### PR TITLE
Increase gas value in static call to handle stETH edge case

### PR DESCRIPTION
**Pull request by majkic99**
balanceOf in stETH contract uses around 38.5k gas, and the calls with 20k gas sent will fail. This will fix that issue

### CODE REVIEW

**Comment by majkic99** [comment]
[0x0c2eb6d303d8b2bc19448e8acfa2d42a3940fd72](https://etherscan.io/address/0x0c2eb6d303d8b2bc19448e8acfa2d42a3940fd72) hotfix for stETH case deployed on mainnet

**Comment by Mrtenz** [comment]
Interesting, this would mean that the maximum number of tokens per call would have to go down by a lot too. The `eth-scan` JS library should handle this case by automatically fetching the balance the traditional way for stETH specifically already, but that wouldn't be as efficient.

I suppose we could make the gas per token contract configurable too?

**Comment by majkic99** [comment]
image
Looking at tenderly simulation sending 45k gas doesn't mean that any leftover gas will be spent, so the amount of tokens per call shouldn't change by much

**Comment by Mrtenz** [comment]
The problem is that _in theory_ each token could now use 45k gas, so the theoretical number of tokens per call would have to go down to prevent running out of gas.

**Pull request closed without merging**
